services:
  - type: web
    name: poster2ics
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OCRSPACE_KEY
        sync: false
      - key: GEMINI_KEY
        sync: false
